// @code-analyzer/infra — Generated File Detector Tests
import { describe, it, expect } from 'vitest';
import { GeneratedFileDetector } from '../generated-detector.js';

describe('GeneratedFileDetector', () => {
  const detector = new GeneratedFileDetector();

  describe('detectByPath — Lock Files', () => {
    it('detects package-lock.json', () => {
      expect(detector.detectByPath('package-lock.json').isGenerated).toBe(true);
    });
    it('detects pnpm-lock.yaml', () => {
      expect(detector.detectByPath('pnpm-lock.yaml').isGenerated).toBe(true);
    });
    it('detects yarn.lock', () => {
      expect(detector.detectByPath('yarn.lock').isGenerated).toBe(true);
    });
    it('detects Cargo.lock', () => {
      expect(detector.detectByPath('Cargo.lock').isGenerated).toBe(true);
    });
  });

  describe('detectByPath — Minified Files', () => {
    it('detects .min.js', () => {
      expect(detector.detectByPath('dist/bundle.min.js').isGenerated).toBe(true);
    });
    it('detects .min.css', () => {
      expect(detector.detectByPath('dist/style.min.css').isGenerated).toBe(true);
    });
  });

  describe('detectByPath — Generated Markers', () => {
    it('detects *.generated.*', () => {
      expect(detector.detectByPath('src/types.generated.ts').isGenerated).toBe(true);
    });
    it('detects *-generated.*', () => {
      expect(detector.detectByPath('src/types-generated.ts').isGenerated).toBe(true);
    });
    it('detects __generated__ directory', () => {
      expect(detector.detectByPath('src/__generated__/types.ts').isGenerated).toBe(true);
    });
  });

  describe('detectByPath — Build Output', () => {
    it('detects dist/', () => {
      expect(detector.detectByPath('dist/bundle.js').isGenerated).toBe(true);
    });
    it('detects build/', () => {
      expect(detector.detectByPath('build/output.js').isGenerated).toBe(true);
    });
    it('detects .next/', () => {
      expect(detector.detectByPath('.next/server/pages/index.js').isGenerated).toBe(true);
    });
    it('detects target/ (Rust)', () => {
      expect(detector.detectByPath('target/debug/lib.rs').isGenerated).toBe(true);
    });
  });

  describe('detectByPath — Code Generation Frameworks', () => {
    it('detects protobuf generated Go', () => {
      expect(detector.detectByPath('protobuf/api.pb.go').isGenerated).toBe(true);
    });
    it('detects protobuf generated Python', () => {
      expect(detector.detectByPath('protobuf/api_pb2.py').isGenerated).toBe(true);
    });
    it('detects GraphQL codegen', () => {
      expect(detector.detectByPath('graphql/generated/types.ts').isGenerated).toBe(true);
    });
    it('detects Prisma client', () => {
      expect(detector.detectByPath('node_modules/.prisma/client/index.js').isGenerated).toBe(true);
    });
  });

  describe('detectByPath — Non-Generated Files', () => {
    it('does not flag regular source files', () => {
      expect(detector.detectByPath('src/components/Button.tsx').isGenerated).toBe(false);
    });
    it('does not flag test files', () => {
      expect(detector.detectByPath('src/components/Button.test.ts').isGenerated).toBe(false);
    });
    it('does not flag config files', () => {
      expect(detector.detectByPath('tsconfig.json').isGenerated).toBe(false);
    });
    it('does not flag package.json', () => {
      expect(detector.detectByPath('package.json').isGenerated).toBe(false);
    });
  });

  describe('detectByContent — Generated Markers', () => {
    it('detects "auto-generated" comment in C-style', () => {
      const r = detector.detectByContent('/* auto-generated file */\ncode');
      expect(r.isGenerated).toBe(true);
    });
    it('detects "DO NOT EDIT" comment', () => {
      const r = detector.detectByContent('// DO NOT EDIT\ncode');
      expect(r.isGenerated).toBe(true);
    });
    it('detects "@generated" annotation', () => {
      const r = detector.detectByContent('// @generated\ncode');
      expect(r.isGenerated).toBe(true);
    });
    it('detects "generated by" comment', () => {
      const r = detector.detectByContent('// generated by protoc\ncode');
      expect(r.isGenerated).toBe(true);
    });
    it('detects Python "auto-generated"', () => {
      const r = detector.detectByContent('# auto-generated file\ncode');
      expect(r.isGenerated).toBe(true);
    });
    it('does not flag normal code', () => {
      const r = detector.detectByContent('function doWork(): void {\n  return;\n}');
      expect(r.isGenerated).toBe(false);
    });
    it('handles empty content', () => {
      const r = detector.detectByContent('');
      expect(r.isGenerated).toBe(false);
    });
  });

  describe('detectFile — Combined Detection', () => {
    it('uses path detection first', () => {
      const r = detector.detectFile('dist/bundle.js', 'function x(){}');
      expect(r.isGenerated).toBe(true);
      expect(r.reason).toContain('build output');
    });
    it('falls back to content detection', () => {
      const r = detector.detectFile('src/unknown.ts', '// auto-generated by tool');
      expect(r.isGenerated).toBe(true);
    });
    it('returns not generated for normal files', () => {
      const r = detector.detectFile('src/app.ts', 'export const App = () => <div/>;');
      expect(r.isGenerated).toBe(false);
    });
  });

  describe('Custom Patterns', () => {
    it('accepts additional patterns', () => {
      const d = new GeneratedFileDetector([
        { pattern: '**/*.mygen.ts', description: 'MyGen output', priority: 99 },
      ]);
      expect(d.detectByPath('src/api.mygen.ts').isGenerated).toBe(true);
    });
    it('accepts regex patterns', () => {
      const d = new GeneratedFileDetector([
        {
          pattern: '^codegen-output/.*\\.ts$',
          isRegex: true,
          description: 'Codegen regex',
          priority: 99,
        },
      ]);
      expect(d.detectByPath('codegen-output/models.ts').isGenerated).toBe(true);
    });
  });
});
