// @code-analyzer/infra — Generated File Detector
// Identifies auto-generated files based on path patterns and content markers.
// Supports detection of lock files, minified files, build output, protobuf/GraphQL
// codegen, and custom patterns.

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratedPattern {
  pattern: string;
  description: string;
  priority: number;
  isRegex?: boolean;
}

export interface GeneratedDetectionResult {
  isGenerated: boolean;
  reason?: string;
}

// ---------------------------------------------------------------------------
// Default Patterns
// ---------------------------------------------------------------------------

const DEFAULT_PATTERNS: GeneratedPattern[] = [
  // Lock files
  { pattern: '**/package-lock.json', description: 'NPM lock file', priority: 100 },
  { pattern: '**/pnpm-lock.yaml', description: 'PNPM lock file', priority: 100 },
  { pattern: '**/yarn.lock', description: 'Yarn lock file', priority: 100 },
  { pattern: '**/Cargo.lock', description: 'Cargo lock file', priority: 100 },
  { pattern: '**/Gemfile.lock', description: 'Bundler lock file', priority: 100 },
  { pattern: '**/poetry.lock', description: 'Poetry lock file', priority: 100 },

  // Minified files
  { pattern: '**/*.min.js', description: 'Minified JavaScript', priority: 90 },
  { pattern: '**/*.min.css', description: 'Minified CSS', priority: 90 },

  // Generated markers in path
  { pattern: '**/*.generated.*', description: 'Generated file marker', priority: 95 },
  { pattern: '**/*-generated.*', description: 'Generated file marker', priority: 95 },
  { pattern: '**/__generated__/**', description: 'Generated directory', priority: 95 },

  // Build output directories
  { pattern: 'dist/**', description: 'build output', priority: 85 },
  { pattern: 'build/**', description: 'build output', priority: 85 },
  { pattern: '.next/**', description: 'Next.js build output', priority: 85 },
  { pattern: 'target/**', description: 'Rust build output', priority: 85 },
  { pattern: 'out/**', description: 'Build output directory', priority: 80 },
  { pattern: '.output/**', description: 'Nuxt build output', priority: 85 },

  // Code generation frameworks
  { pattern: '**/*.pb.go', description: 'Protobuf generated Go', priority: 95 },
  { pattern: '**/*_pb2.py', description: 'Protobuf generated Python', priority: 95 },
  { pattern: '**/generated/**', description: 'GraphQL codegen output', priority: 90 },
  {
    pattern: '**/node_modules/.prisma/client/**',
    description: 'Prisma generated client',
    priority: 90,
  },
  { pattern: '**/*.pb.ts', description: 'Protobuf generated TypeScript', priority: 95 },
  { pattern: '**/*.grpc.*', description: 'gRPC generated code', priority: 95 },
];

// Content markers indicating generated files
const GENERATED_CONTENT_MARKERS = [
  /\/\*\s*auto-generated/i,
  /\/\/\s*auto-generated/i,
  /#\s*auto-generated/i,
  /\/\/\s*DO NOT EDIT/i,
  /\/\*\s*DO NOT EDIT/i,
  /#\s*DO NOT EDIT/i,
  /\/\/\s*@generated/i,
  /\/\*\s*@generated/i,
  /\/\/\s*generated by/i,
  /\/\*\s*generated by/i,
  /#\s*generated by/i,
];

// ---------------------------------------------------------------------------
// GeneratedFileDetector
// ---------------------------------------------------------------------------

export class GeneratedFileDetector {
  private patterns: GeneratedPattern[];

  constructor(customPatterns?: GeneratedPattern[]) {
    this.patterns = [...DEFAULT_PATTERNS];
    if (customPatterns) {
      // Sort all patterns by priority (highest first)
      this.patterns = [...this.patterns, ...customPatterns].sort(
        (a, b) => (b.priority ?? 0) - (a.priority ?? 0),
      );
    }
  }

  detectByPath(filePath: string): GeneratedDetectionResult {
    // Normalize path: use forward slashes
    const normalized = filePath.replace(/\\/g, '/');
    /* v8 ignore next */ // defensive: split always returns at least one element for valid paths
    const base = normalized.split('/').pop() ?? normalized;

    for (const p of this.patterns) {
      if (p.isRegex) {
        const regex = new RegExp(p.pattern);
        if (regex.test(normalized) || regex.test(base)) {
          return { isGenerated: true, reason: p.description };
        }
      } else if (this.matchGlob(normalized, p.pattern)) {
        return { isGenerated: true, reason: p.description };
      }
    }

    return { isGenerated: false };
  }

  detectByContent(content: string): GeneratedDetectionResult {
    if (!content) {
      return { isGenerated: false };
    }

    for (const marker of GENERATED_CONTENT_MARKERS) {
      if (marker.test(content)) {
        return { isGenerated: true };
      }
    }

    return { isGenerated: false };
  }

  detectFile(filePath: string, content: string): GeneratedDetectionResult {
    // Try path-based detection first
    const pathResult = this.detectByPath(filePath);
    if (pathResult.isGenerated) {
      return pathResult;
    }

    // Fall back to content-based detection
    const contentResult = this.detectByContent(content);
    if (contentResult.isGenerated) {
      return { isGenerated: true, reason: 'Content contains generated marker' };
    }

    return { isGenerated: false };
  }

  // ---------------------------------------------------------------------------
  // Private: Simple glob matching
  // ---------------------------------------------------------------------------

  private matchGlob(filePath: string, pattern: string): boolean {
    const regexStr = pattern
      .replace(/[.+^${}()|[\]\\]/g, '\\$&')
      // Use placeholder tokens to prevent later steps from modifying
      // the replacement strings (e.g., * and ? in (?:.*/)?)
      .replace(/\*\*\//g, '\x00')
      .replace(/\*\*/g, '\x01')
      .replace(/\*/g, '[^/]*')
      .replace(/\?/g, '.')
      .replace(/\x00/g, '(?:.*/)?')
      .replace(/\x01/g, '.*');

    const regex = new RegExp(`^${regexStr}$`);
    return regex.test(filePath);
  }
}
