// @code-analyzer/infra — Generated File Detector
// Detects auto-generated files using configurable filename patterns and
// content heuristics. Helps avoid noise in code reviews by excluding
// files that are produced by code generators, bundlers, or compilers.

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GeneratedFileResult {
  /** Whether the file is classified as generated. */
  isGenerated: boolean;
  /** The matched pattern that classified it, or null if not generated. */
  matchedPattern: string | null;
  /** Human-readable reason for the classification. */
  reason: string;
}

export interface GeneratedFilePattern {
  /** Glob or regex pattern to match against the file path. */
  pattern: string;
  /** Whether the pattern is a regex (default: glob). */
  isRegex?: boolean;
  /** Human-readable description of this pattern. */
  description: string;
  /** Priority: higher-priority patterns are checked first. */
  priority?: number;
}

// ---------------------------------------------------------------------------
// Default Patterns
// ---------------------------------------------------------------------------

const DEFAULT_GENERATED_PATTERNS: GeneratedFilePattern[] = [
  // Package manager lock files
  { pattern: '**/package-lock.json', description: 'npm lock file', priority: 100 },
  { pattern: '**/pnpm-lock.yaml', description: 'pnpm lock file', priority: 100 },
  { pattern: '**/yarn.lock', description: 'yarn lock file', priority: 100 },
  { pattern: '**/Gemfile.lock', description: 'bundler lock file', priority: 100 },
  { pattern: '**/Cargo.lock', description: 'cargo lock file', priority: 100 },
  { pattern: '**/poetry.lock', description: 'poetry lock file', priority: 100 },
  { pattern: '**/Pipfile.lock', description: 'pipenv lock file', priority: 100 },
  { pattern: '**/composer.lock', description: 'composer lock file', priority: 100 },

  // Minified files
  { pattern: '**/*.min.js', description: 'minified JavaScript', priority: 95 },
  { pattern: '**/*.min.css', description: 'minified CSS', priority: 95 },
  { pattern: '**/*.min.js.map', description: 'minified JS source map', priority: 90 },

  // Generated code
  { pattern: '**/*.generated.*', description: 'explicitly marked as generated', priority: 100 },
  { pattern: '**/*-generated.*', description: 'explicitly marked as generated', priority: 100 },
  { pattern: '**/*_generated.*', description: 'explicitly marked as generated', priority: 100 },
  { pattern: '**/*.gen.*', description: 'generated file', priority: 95 },

  // Compiler output
  { pattern: '**/dist/**', description: 'build output (dist)', priority: 90 },
  { pattern: '**/build/**', description: 'build output (build)', priority: 90 },
  { pattern: '**/.next/**', description: 'Next.js build output', priority: 90 },
  { pattern: '**/.nuxt/**', description: 'Nuxt build output', priority: 90 },
  { pattern: '**/out/**', description: 'output directory', priority: 85 },
  { pattern: '**/target/**', description: 'Rust build output', priority: 85 },
  { pattern: '**/__pycache__/**', description: 'Python bytecode cache', priority: 95 },

  // Code generation frameworks
  { pattern: '**/protobuf/**/*.pb.go', description: 'protobuf generated Go', priority: 98 },
  { pattern: '**/protobuf/**/*_pb2.py', description: 'protobuf generated Python', priority: 98 },
  { pattern: '**/protobuf/**/*_pb2.pyi', description: 'protobuf generated Python typing', priority: 98 },
  { pattern: '**/*.pb.go', description: 'protobuf generated Go', priority: 90 },
  { pattern: '**/*_pb2.py', description: 'protobuf generated Python', priority: 90 },
  { pattern: '**/*.pb.ts', description: 'protobuf generated TypeScript', priority: 90 },
  { pattern: '**/generated/**/*.ts', description: 'generated TypeScript directory', priority: 90 },
  { pattern: '**/__generated__/**', description: 'generated code directory', priority: 95 },
  { pattern: '**/auto-generated/**', description: 'auto-generated code', priority: 95 },

  // GraphQL codegen
  { pattern: '**/graphql/generated/**', description: 'GraphQL codegen output', priority: 95 },
  { pattern: '**/*.graphql.ts', description: 'GraphQL generated TypeScript', priority: 85 },

  // OpenAPI/Swagger codegen
  { pattern: '**/swagger-generated/**', description: 'Swagger codegen output', priority: 95 },
  { pattern: '**/openapi-generated/**', description: 'OpenAPI codegen output', priority: 95 },

  // Prisma generated
  { pattern: '**/node_modules/.prisma/client/**', description: 'Prisma generated client', priority: 98 },
  { pattern: '**/@prisma/client/**', description: 'Prisma generated client', priority: 95 },

  // TypeScript declaration files generated by build
  { pattern: '**/*.d.ts.map', description: 'TypeScript declaration map', priority: 85 },

  // Migration files (often auto-generated)
  { pattern: '**/migrations/**/*.sql', description: 'database migration', priority: 50 },
  { pattern: '**/migrations/**/*.ts', description: 'database migration', priority: 50 },
  { pattern: '**/alembic/versions/**', description: 'Alembic migration', priority: 50 },

  // IDE configuration
  { pattern: '**/.idea/**', description: 'JetBrains IDE config', priority: 95 },
  { pattern: '**/.vscode/settings.json', description: 'VS Code workspace settings', priority: 80 },

  // Git generated
  { pattern: '**/.git/HEAD', description: 'git internals', priority: 100 },
  { pattern: '**/.git/index', description: 'git internals', priority: 100 },
];

// ---------------------------------------------------------------------------
// Content-Based Detection Heuristics
// ---------------------------------------------------------------------------

const GENERATED_COMMENT_PATTERNS = [
  /\/\*\s*auto-generated/i,
  /\/\*\s*automatically generated/i,
  /\/\/\s*auto-generated/i,
  /\/\/\s*this file is auto-generated/i,
  /\/\/\s*generated by/i,
  /\/\/\s*do not edit/i,
  /#\s*auto-generated/i,
  /#\s*this file is auto-generated/i,
  /#\s*do not edit/i,
  /\/\/\s*@generated/i,
  /\/\*\s*@generated/i,
];

const MAX_CONTENT_CHECK_LINES = 20;

// ---------------------------------------------------------------------------
// Generated File Detector
// ---------------------------------------------------------------------------

export class GeneratedFileDetector {
  private readonly patterns: GeneratedFilePattern[];

  constructor(additionalPatterns: GeneratedFilePattern[] = []) {
    this.patterns = [
      ...additionalPatterns,
      ...DEFAULT_GENERATED_PATTERNS,
    ].sort((a, b) => (b.priority ?? 50) - (a.priority ?? 50));
  }

  /**
   * Detect if a file is generated based on its path.
   *
   * @param filePath — file path (relative or absolute, normalized with /)
   * @returns GeneratedFileResult with classification details
   */
  detectByPath(filePath: string): GeneratedFileResult {
    const normalized = filePath.replace(/\\/g, '/');

    for (const pattern of this.patterns) {
      if (this.matchPattern(normalized, pattern)) {
        return {
          isGenerated: true,
          matchedPattern: pattern.pattern,
          reason: pattern.description,
        };
      }
    }

    return {
      isGenerated: false,
      matchedPattern: null,
      reason: 'No generated file pattern matched',
    };
  }

  /**
   * Detect if a file is generated based on its content.
   * Checks the first N lines for common "auto-generated" markers.
   *
   * @param content — the file content (first 1KB is sufficient)
   * @returns GeneratedFileResult with classification details
   */
  detectByContent(content: string): GeneratedFileResult {
    if (!content || content.trim().length === 0) {
      return {
        isGenerated: false,
        matchedPattern: null,
        reason: 'Empty content',
      };
    }

    const lines = content.split('\n').slice(0, MAX_CONTENT_CHECK_LINES);

    for (const line of lines) {
      for (const pattern of GENERATED_COMMENT_PATTERNS) {
        if (pattern.test(line)) {
          return {
            isGenerated: true,
            matchedPattern: pattern.source,
            reason: `Content marker: "${line.trim().slice(0, 80)}"`,
          };
        }
      }
    }

    return {
      isGenerated: false,
      matchedPattern: null,
      reason: 'No generated content markers found',
    };
  }

  /**
   * Combined detection: checks both path and content.
   *
   * @param filePath — file path
   * @param content — first 1KB of file content (optional)
   */
  detectFile(filePath: string, content?: string): GeneratedFileResult {
    const pathResult = this.detectByPath(filePath);
    if (pathResult.isGenerated) return pathResult;

    if (content) {
      return this.detectByContent(content);
    }

    return pathResult;
  }

  // ---------------------------------------------------------------------------
  // Private Helpers
  // ---------------------------------------------------------------------------

  private matchPattern(filePath: string, pattern: GeneratedFilePattern): boolean {
    if (pattern.isRegex) {
      return new RegExp(pattern.pattern).test(filePath);
    }
    return this.globMatch(pattern.pattern, filePath);
  }

  private globMatch(glob: string, filePath: string): boolean {
    // Convert glob to regex for matching
    const placeholder = '\x00';
    let result = glob;

    // Replace **/ first (matches zero or more directories)
    result = result.replace(/\*\*\//g, placeholder + 'DS' + placeholder);

    // Replace ** (matches any number of characters including /)
    result = result.replace(/\*\*/g, placeholder + 'DA' + placeholder);

    // Replace * (matches any non-separator characters)
    result = result.replace(/\*/g, placeholder + 'S' + placeholder);

    // Replace ? (single non-separator character)
    result = result.replace(/\?/g, placeholder + 'Q' + placeholder);

    // Escape regex special characters
    result = result.replace(/[.+^${}()|[\]\\]/g, '\\$&');

    // Replace placeholders with regex patterns
    result = result.replace(
      new RegExp(placeholder + 'DS' + placeholder, 'g'),
      '(?:.+/)?',
    );
    result = result.replace(
      new RegExp(placeholder + 'DA' + placeholder, 'g'),
      '.*',
    );
    result = result.replace(
      new RegExp(placeholder + 'S' + placeholder, 'g'),
      '[^/]*',
    );
    result = result.replace(
      new RegExp(placeholder + 'Q' + placeholder, 'g'),
      '[^/]',
    );

    return new RegExp(`^${result}$`).test(filePath);
  }
}
